basePath: /
definitions:
  message.LoginRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  message.LoginResponse:
    properties:
      accessToken:
        type: string
      email:
        type: string
      name:
        type: string
      playerId:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample description.
  title: Account Service Learning API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns simple OK
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - health
  /registerOrLogin:
    post:
      consumes:
      - application/json
      description: Register a new account if not exist, otherwise login
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/message.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.LoginResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Register or Login
      tags:
      - account
swagger: "2.0"
